// src/lib/default-kb.ts
import type { StoredState } from '@/stores/useToolsStore';

// This is a static representation of the default knowledge base,
// ensuring reliable loading without parsing text on startup.
export const defaultKnowledgeBase: StoredState = {
  triggers: [
    {
      id: 'trigger-apps',
      name: 'Aplicativos',
      subOptions: [
        {
          id: 'so-app-open-close',
          name: 'Aplicativo aberto/fechado',
          telas: [
            { id: 't-app-1', content: 'Tela 1:  Selecione uma opção  [ ]   Aplicativo aberto [ ]   Aplicativo fechado  ( ) Forçar mecanismo antigo:  Tente esta opção se você tiver problemas com a implementação do novo gatilho de aplicativo aberto ou se não quiser que o MacroDroid obtenha permissão de acessibilidade.  CANCELAR | OK' },
            { id: 't-app-2', content: 'Tela 2: Ex.: [ X ] Aplicativo Aberto  Selecione uma opção  [ ] Selecionar Aplicativo(a) [ ] Digite o nome do pacote  CANCELAR | OK  ---  Obs: Todas as telas após a tela 1 em todas as sub opções são telas exemplares, com o intuito de instruir a IA como seria a próxima tela após a tela 1, para criar um plano mais conciso e real e detalhado  O Macrodroid Permite múltiplos gatilhos, ações e restrições numa única macro, bem como permite gatilhos, ações e restrições repetidas.' },
            { id: 't-app-3', content: 'Tela 3: [ X ] Selecionar Aplicativo(s)  Selecionar Aplicativo(s)  [...Lista de aplicativos selecionáveis...]  ( ) Exibir aplicativos não executáveis  TUDO   | CANCELAR | OK' },
          ]
        },
        { id: 'so-app-install', name: 'Aplicativo instalado/desinstalado/atualizado', telas: [] },
        { id: 'so-app-ui-click', name: 'Clique na IU', telas: [] },
        { id: 'so-app-screenshot', name: 'Conteúdo da captura de ecrã', telas: [] },
        { id: 'so-app-screen-content', name: 'Conteúdo da tela', telas: [] },
        { id: 'so-app-tasker', name: 'Plugin Tasker/Locale', telas: [] },
        { id: 'so-app-spotify', name: 'Spotify', telas: [] },
        { id: 'so-app-shared-text', name: 'Texto partilhado com o MacroDroid', telas: [] },
      ],
    },
    {
      id: 'trigger-battery',
      name: 'Bateria/Potência',
      subOptions: [
        { id: 'so-battery-side-button', name: 'Botão lateral pressionado várias vezes', telas: [] },
        { id: 'so-battery-charger', name: 'Carregador conectado/desconectado', telas: [] },
        { id: 'so-battery-saver', name: 'Estado da Economia de Bateria', telas: [] },
        { id: 'so-battery-level', name: 'Nível da bateria', telas: [] },
        { id: 'so-battery-temp', name: 'Temperatura da bateria', telas: [] },
      ],
    },
    {
      id: 'trigger-calls',
      name: 'Chamadas/SMS',
      subOptions: [
        { id: 'so-call-active', name: 'Chamada ativa', telas: [] },
        { id: 'so-call-made', name: 'Chamada efetuada', telas: [] },
        { id: 'so-call-ended', name: 'Chamada encerrada', telas: [] },
        { id: 'so-call-missed', name: 'Chamada perdida', telas: [] },
        { id: 'so-call-received', name: 'Chamada recebida', telas: [] },
        { id: 'so-call-dialed', name: 'Número de telefone discado', telas: [] },
        { id: 'so-sms-sent', name: 'SMS enviado', telas: [] },
        { id: 'so-sms-received', name: 'SMS recebido', telas: [] },
      ],
    },
    {
      id: 'trigger-connectivity',
      name: 'Conectividade',
      subOptions: [
        { id: 'so-conn-wear', name: 'Android Wear', telas: [] },
        { id: 'so-conn-beacon', name: 'Beacon dentro/fora do alcance', telas: [] },
        { id: 'so-conn-internet', name: 'Conectividade com internet modificada', telas: [] },
        { id: 'so-conn-usb', name: 'Dispositivo USB conectado/desconectado', telas: [] },
        { id: 'so-conn-bt', name: 'Estado do Bluetooth', telas: [] },
        { id: 'so-conn-headset', name: 'Fone de ouvido inserido/removido', telas: [] },
        { id: 'so-conn-wifi-state', name: 'Mudança de Estado do Wi-Fi', telas: [] },
        { id: 'so-conn-ip', name: 'Mudança de endereço IP', telas: [] },
        { id: 'so-conn-vpn', name: 'Mudança de estado do VPN', telas: [] },
        { id: 'so-conn-http', name: 'Pedido do servidor HTTP', telas: [] },
        { id: 'so-conn-hotspot', name: 'Ponto de acesso habilitado/desabilitado', telas: [] },
        { id: 'so-conn-roaming', name: 'Roaming iniciado/interrompido', telas: [] },
        { id: 'so-conn-signal', name: 'Status do sinal de celular', telas: [] },
        { id: 'so-conn-webhook', name: 'Webhook (URL)', telas: [] },
        { id: 'so-conn-wifi-range', name: 'Wi-Fi dentro/fora do alcance', telas: [] },
      ],
    },
    {
      id: 'trigger-datetime',
      name: 'Data/Hora',
      subOptions: [
        { id: 'so-dt-stopwatch', name: 'Cronômetro', telas: [] },
        { id: 'so-dt-dayofweek', name: 'Dia da semana/mês', telas: [] },
        { id: 'so-dt-calendar', name: 'Evento de calendário', telas: [] },
        { id: 'so-dt-trigger', name: 'Gatilho de dia/hora', telas: [] },
        { id: 'so-dt-interval', name: 'Intervalo regular', telas: [] },
        { id: 'so-dt-sun', name: 'Nascer/Pôr do sol', telas: [] },
      ],
    },
    {
      id: 'trigger-macrodroid',
      name: 'Específico do MacroDroid',
      subOptions: [
        { id: 'so-md-mode', name: 'Alteração do Modo MacroDroid', telas: [] },
        { id: 'so-md-sidebar', name: 'Barra lateral aberta/fechada', telas: [] },
        { id: 'so-md-quicktile', name: 'Bloco das configurações rápidas', telas: [] },
        { id: 'so-md-notifybar', name: 'Botão da barra de notificação', telas: [] },
        { id: 'so-md-syslog', name: 'Entrada de registro do sistema', telas: [] },
        { id: 'so-md-empty', name: 'Gatilho vazio', telas: [] },
        { id: 'so-md-macro-complete', name: 'Macro concluída', telas: [] },
        { id: 'so-md-macro-enabled', name: 'Macro habilitada', telas: [] },
        { id: 'so-md-init', name: 'MacroDroid inicializado', telas: [] },
        { id: 'so-md-variable', name: 'Variável do MacroDroid modificada', telas: [] },
      ],
    },
    {
      id: 'trigger-device-events',
      name: 'Eventos do Dispositivo',
      subOptions: [
        { id: 'so-dev-autosync', name: 'Auto-sincronização modificada', telas: [] },
        { id: 'so-dev-daydream', name: 'Daydream ligado/desligado', telas: [] },
        { id: 'so-dev-dock', name: 'Dispositivo dentro/fora do dock', telas: [] },
        { id: 'so-dev-boot', name: 'Dispositivo inicializado', telas: [] },
        { id: 'so-dev-unlock-fail', name: 'Falha na tentativa de desbloqueio', telas: [] },
        { id: 'so-dev-photo', name: 'Foto tirada', telas: [] },
        { id: 'so-dev-gps', name: 'GPS ativado/desativado', telas: [] },
        { id: 'so-dev-intent', name: 'Intent recebido', telas: [] },
        { id: 'so-dev-logcat', name: 'Mensagem do Logcat', telas: [] },
        { id: 'so-dev-airplane', name: 'Modo Avião Alterado', telas: [] },
        { id: 'so-dev-dnd', name: 'Modo Prioritário / Não Perturbe', telas: [] },
        { id: 'so-dev-silent', name: 'Modo Silencioso Ativado/Desativado', telas: [] },
        { id: 'so-dev-sim', name: 'Mudança do cartão SIM', telas: [] },
        { id: 'so-dev-sys-setting', name: 'Mudança em configuração de sistema', telas: [] },
        { id: 'so-dev-music', name: 'Música/Som tocando', telas: [] },
        { id: 'so-dev-notification', name: 'Notificação', telas: [] },
        { id: 'so-dev-autorotate', name: 'Rotação automática modificada', telas: [] },
        { id: 'so-dev-unlocked', name: 'Tela desbloqueada', telas: [] },
        { id: 'so-dev-screen', name: 'Tela ligada/desligada', telas: [] },
        { id: 'so-dev-dark-theme', name: 'Troca do tema Escuro', telas: [] },
        { id: 'so-dev-clipboard', name: 'Área de transferência modificada', telas: [] },
      ],
    },
    {
      id: 'trigger-user-interaction',
      name: 'Interação do Usuário',
      subOptions: [
        { id: 'so-user-shortcut', name: 'Atalho iniciado', telas: [] },
        { id: 'so-user-media-v2', name: 'Botão de Mídia V2', telas: [] },
        { id: 'so-user-media-press', name: 'Botão de mídia pressionado', telas: [] },
        { id: 'so-user-volume-press', name: 'Botão de volume pressionado', telas: [] },
        { id: 'so-user-widget', name: 'Botão de widget pressionado', telas: [] },
        { id: 'so-user-floating-button', name: 'Botão flutuante', telas: [] },
        { id: 'so-user-swipe', name: 'Deslize na tela', telas: [] },
        { id: 'so-user-fingerprint', name: 'Gesto de impressão digital', telas: [] },
        { id: 'so-user-assistant', name: 'Google Assistente', telas: [] },
        { id: 'so-user-home-long', name: 'Pressionamento longo do botão Home', telas: [] },
        { id: 'so-user-volume-long', name: 'Pressionamento longo do botão de volume', telas: [] },
        { id: 'so-user-power-long', name: 'Pressão longa do botão liga / desliga', telas: [] },
      ],
    },
    {
      id: 'trigger-location',
      name: 'Localização',
      subOptions: [
        { id: 'so-loc-location', name: 'Localização', telas: [] },
        { id: 'so-loc-geofence', name: 'Perímetro geográfico', telas: [] },
        { id: 'so-loc-weather', name: 'Tempo', telas: [] },
        { id: 'so-loc-cell-tower', name: 'Torre de celular modificada', telas: [] },
      ],
    },
    {
      id: 'trigger-sensors',
      name: 'Sensores',
      subOptions: [
        { id: 'so-sensor-activity', name: 'Atividade reconhecida', telas: [] },
        { id: 'so-sensor-shake', name: 'Dispositivo agitado', telas: [] },
        { id: 'so-sensor-flip', name: 'Dispositivo virado', telas: [] },
        { id: 'so-sensor-orientation', name: 'Orientação da tela', telas: [] },
        { id: 'so-sensor-light', name: 'Sensor de luz', telas: [] },
        {
          id: 'so-sensor-proximity',
          name: 'Sensor de proximidade',
          telas: [{ id: 't-sensor-prox-1', content: 'Tela 1  * Selecione uma opção  [ ] Aproximado [ ] Afastado [ ] Aceno lento [ ] Aceno rápido  CANCELAR | OK' }],
        },
        { id: 'so-sensor-sleep', name: 'Sono', telas: [] },
      ],
    },
  ],
  actions: [
    {
      id: 'action-device',
      name: 'Ações do dispositivo',
      subOptions: [
        { id: 'so-act-dev-home', name: 'Abrir tela inicial', telas: [] },
        {
          id: 'so-act-dev-auth',
          name: 'Autenticar usuário',
          telas: [{ id: 't-act-dev-auth-1', content: 'Tela 1:  Autenticar Usuário  Título: [Título...] | [...] -> Botão com lista de palavras mágicas somente entre "{ }"  Legenda: [Legenda...] | [...]  Salvar em variável \\/ -> (Botão de seta pra baixo para abrir lista de variáveis criadas) | "+" -> (Botão para criar uma nova variável)  [ ] Permitir PIN / Padrão  CANCELAR | OK' }],
        },
        { id: 'so-act-dev-voice-input', name: 'Entrada de voz', telas: [] },
        { id: 'so-act-dev-statusbar', name: 'Expandir/recolher a barra de status', telas: [] },
        { id: 'so-act-dev-speak', name: 'Falar texto', telas: [] },
        { id: 'so-act-dev-ui-interact', name: 'Interação com UI', telas: [] },
        { id: 'so-act-dev-torch', name: 'Ligar/desligar a Lanterna', telas: [] },
        { id: 'so-act-dev-light-level', name: 'Obter nível de luz', telas: [] },
        { id: 'so-act-dev-share-text', name: 'Partilhar texto', telas: [] },
        { id: 'so-act-dev-voice-search', name: 'Pesquisa de voz', telas: [] },
        { id: 'so-act-dev-clipboard-fill', name: 'Preencher a área de transferência', telas: [] },
        { id: 'so-act-dev-back-button', name: 'Pressionar o botão voltar', telas: [] },
        { id: 'so-act-dev-clipboard-reload', name: 'Recarregar área de transferência', telas: [] },
        { id: 'so-act-dev-android-features', name: 'Recursos do Android', telas: [] },
        { id: 'so-act-dev-vibrate', name: 'Vibrar', telas: [] },
      ],
    },
    {
      id: 'action-apps',
      name: 'Aplicativos',
      subOptions: [
        { id: 'so-act-app-open', name: 'Abrir aplicativo', telas: [] },
        { id: 'so-act-app-website', name: 'Abrir site', telas: [] },
        { id: 'so-act-app-js', name: 'Código JavaScript', telas: [] },
        { id: 'so-act-app-kill', name: 'Fechar aplicativo em segundo plano', telas: [] },
        { id: 'so-act-app-shortcut', name: 'Iniciar atalho', telas: [] },
        { id: 'so-act-app-activity', name: 'Iniciar atividade da aplicação', telas: [] },
        { id: 'so-act-app-get-installed', name: 'Obter aplicações instaladas', telas: [] },
        { id: 'so-act-app-tasker', name: 'Plugin Tasker/Locale', telas: [] },
        { id: 'so-act-app-shell', name: 'Script de Shell', telas: [] },
      ],
    },
    {
      id: 'action-files',
      name: 'Arquivos',
      subOptions: [
        { id: 'so-act-file-open', name: 'Abrir arquivo', telas: [] },
        { id: 'so-act-file-write', name: 'Escrever em arquivo', telas: [] },
        { id: 'so-act-file-manage', name: 'Gerenciar arquivo', telas: [] },
        { id: 'so-act-file-read', name: 'Ler de arquivo', telas: [] },
      ],
    },
    {
      id: 'action-camera',
      name: 'Câmera/Foto',
      subOptions: [
        { id: 'so-act-cam-last-photo', name: 'Abrir última foto', telas: [] },
        { id: 'so-act-cam-screenshot', name: 'Capturar a tela', telas: [] },
        { id: 'so-act-cam-share-last', name: 'Compartilhar última foto', telas: [] },
        { id: 'so-act-cam-enable-disable', name: 'Habilitar/Desabilitar Câmera', telas: [] },
        { id: 'so-act-cam-take-photo', name: 'Tirar foto', telas: [] },
      ],
    },
    {
      id: 'action-conditions',
      name: 'Condições/Loops',
      subOptions: [
        {
          id: 'so-act-cond-if',
          name: 'Condição Se',
          telas: [
            { id: 't-act-cond-if-1', content: 'Tela 1:  Condição Se  Adicione uma ou mais condições que devem ser satisfeitas em sequência para que as ações dentro da cláusula "Se" sejam executadas.  Condições | +  [Lista de condições adicionadas]  ( ) Não registrar falha se a condição não for satisfeita  CANCELAR | OK  ---  Obs: Se a lista de condições for mais de uma ao lado do "+" na mesma tela aparecerá um "OU" e um "E" para escolher.' },
            { id: 't-act-cond-if-2', content: 'Tela especial:  Em ações se clicar na condição "Se" terá essas opções na tela em pop-up:  - Configurar - Condição de ensaio - Adicionar ação acima - Adicionar ação dependente - Adicionar cláusula senão/se - Adicionar cláusula senão/se confirmada - Adicionar comentário - Recortar - Copiar - Colar ação acima - Extrair para blocos de ações - Excluir - Excluir (Inclusive dependentes) - Desativar - Desativar (Inclusive dependentes) - Ajuda' },
          ],
        },
        { id: 'so-act-cond-confirm', name: 'Confirmar próxima ação', telas: [] },
        { id: 'so-act-cond-iterate', name: 'Iterar Dicionário/Lista', telas: [] },
        { id: 'so-act-cond-break', name: 'Parada do loop', telas: [] },
        { id: 'so-act-cond-repeat', name: 'Repetir ações', telas: [] },
        { id: 'so-act-cond-if-confirmed', name: 'Se confirmado então', telas: [] },
        { id: 'so-act-cond-continue', name: 'Continuar o loop', telas: [] },
      ],
    },
    {
      id: 'action-connectivity',
      name: 'Conectividade',
      subOptions: [
        { id: 'so-act-conn-wear', name: 'Android Wear', telas: [] },
        { id: 'so-act-conn-airplane', name: 'Ativar/desativar modo avião', telas: [] },
        { id: 'so-act-conn-check', name: 'Checar conectividade', telas: [] },
        { id: 'so-act-conn-bt', name: 'Configurar Bluetooth', telas: [] },
        { id: 'so-act-conn-wifi', name: 'Configurar Wi-Fi', telas: [] },
        { id: 'so-act-conn-intent', name: 'Enviar intent', telas: [] },
        { id: 'so-act-conn-hotspot', name: 'Ligar/Desligar ponto de acesso', telas: [] },
        { id: 'so-act-conn-mobile-data', name: 'Ligar/desligar dados móveis', telas: [] },
        { id: 'so-act-conn-autosync', name: 'Ligar/desligar sincronização automática', telas: [] },
        { id: 'so-act-conn-sync-account', name: 'Sincronizar conta', telas: [] },
      ],
    },
    {
        id: 'action-device-settings',
        name: 'Configurações do dispositivo',
        subOptions: [
          { id: 'so-act-devset-secure', name: 'Aplicativo "Secure Settings"', telas: [] },
          { id: 'so-act-devset-daydream', name: 'Ativar Daydream/Protetor de Tela', telas: [] },
          { id: 'so-act-devset-quicktile', name: 'Configurar bloco nas configurações rápidas', telas: [] },
          { id: 'so-act-devset-lockscreen', name: 'Configurar o bloqueio de tela', telas: [] },
          { id: 'so-act-devset-system', name: 'Configuração do Sistema', telas: [] },
          { id: 'so-act-devset-assistant', name: 'Definir assistente digital', telas: [] },
          { id: 'so-act-devset-wallpaper', name: 'Definir papel de parede', telas: [] },
          { id: 'so-act-devset-density', name: 'Densidade do ecrã', telas: [] },
          { id: 'so-act-devset-battery-saver', name: 'Economia de Bateria', telas: [] },
          { id: 'so-act-devset-font-scale', name: 'Escala de Fonte', telas: [] },
          { id: 'so-act-devset-invert-colors', name: 'Inverter Cores', telas: [] },
          { id: 'so-act-devset-autorotate', name: 'Ligar/desligar a rotação automática', telas: [] },
          { id: 'so-act-devset-car-mode', name: 'Modo Carro', telas: [] },
          { id: 'so-act-devset-demo-mode', name: 'Modo de demonstração', telas: [] },
          { id: 'so-act-devset-immersive-mode', name: 'Modo imersivo', telas: [] },
          { id: 'so-act-devset-keyboard', name: 'Selecionar teclado', telas: [] },
          { id: 'so-act-devset-accessibility', name: 'Serviço de Acessibilidade', telas: [] },
          { id: 'so-act-devset-keyboard-default', name: 'Teclado - Definir padrão', telas: [] },
          { id: 'so-act-devset-ambient', name: 'Tela ambiente', telas: [] },
          { id: 'so-act-devset-dark-theme', name: 'Tema Escuro', telas: [] },
        ],
      },
      {
        id: 'action-datetime',
        name: 'Data/Hora',
        subOptions: [
          { id: 'so-act-dt-stopwatch', name: 'Cronômetro', telas: [] },
          { id: 'so-act-dt-alarm', name: 'Despertador', telas: [] },
          { id: 'so-act-dt-speak-time', name: 'Dizer a hora atual', telas: [] },
        ],
      },
      {
        id: 'action-macrodroid',
        name: 'Específico do MacroDroid',
        subOptions: [
          { id: 'so-act-md-category', name: 'Ativar/Desativar categoria', telas: [] },
          { id: 'so-act-md-trigger-enable', name: 'Ativar/desativar gatilho', telas: [] },
          { id: 'so-act-md-empty', name: 'Ação Vazia', telas: [] },
          { id: 'so-act-md-sidebar', name: 'Barra lateral do MacroDroid', telas: [] },
          { id: 'so-act-md-dialog-options', name: 'Caixa de diálogo de opções', telas: [] },
          { id: 'so-act-md-dialog-select', name: 'Caixa de diálogo de seleção', telas: [] },
          { id: 'so-act-md-floating-button', name: 'Configurar Botão Flutuante', telas: [] },
          { id: 'so-act-md-settings', name: 'Configurações do MacroDroid', telas: [] },
          { id: 'so-act-md-set-mode', name: 'Definir o modo do MacroDroid', telas: [] },
          { id: 'so-act-md-set-notify-text', name: 'Definir o texto da notificação do MacroDroid', telas: [] },
          { id: 'so-act-md-set-icon', name: 'Definir ícone do MacroDroid', telas: [] },
          { id: 'so-act-md-set-buttonbar-icon', name: 'Definir ícone na barra de botões', telas: [] },
          { id: 'so-act-md-disable', name: 'Desabilitar Macrodroid', telas: [] },
          { id: 'so-act-md-wait-trigger', name: 'Esperar por disparo', telas: [] },
          { id: 'so-act-md-export', name: 'Exportar macros', telas: [] },
          { id: 'so-act-md-clear-dialog', name: 'Limpar caixa de diálogo MacroDroid', telas: [] },
          { id: 'so-act-md-manipulate-text', name: 'Manipular texto', telas: [] },
          { id: 'so-act-md-widget-button', name: 'Modificar botão de widget', telas: [] },
          { id: 'so-act-md-floating-text', name: 'Texto flutuante', telas: [] },
          { id: 'so-act-md-translate', name: 'Traduzir texto', telas: [] },
        ],
      },
      {
        id: 'action-web',
        name: 'Interação Web',
        subOptions: [
          { id: 'so-act-web-udp', name: 'Comando UDP', telas: [] },
          { id: 'so-act-web-json-parse', name: 'Processar JSON', telas: [] },
          { id: 'so-act-web-json-produce', name: 'Produzir JSON', telas: [] },
          { id: 'so-act-web-http', name: 'Requisição HTTP', telas: [] },
          { id: 'so-act-web-http-response', name: 'Resposta do servidor HTTP', telas: [] },
        ],
      },
      {
        id: 'action-location',
        name: 'Localização',
        subOptions: [
          { id: 'so-act-loc-share', name: 'Compartilhar localização', telas: [] },
          { id: 'so-act-loc-update-freq', name: 'Definir frequência de atualização do local', telas: [] },
          { id: 'so-act-loc-force-update', name: 'Forçar atualização do local', telas: [] },
          { id: 'so-act-loc-mode', name: 'Modo da localização', telas: [] },
        ],
      },
      {
        id: 'action-macros',
        name: 'Macros',
        subOptions: [
          { id: 'so-act-macro-wait', name: 'Aguardar antes da próxima ação', telas: [] },
          { id: 'so-act-macro-enable-disable', name: 'Ativar/Desativar macro', telas: [] },
          { id: 'so-act-macro-action-block', name: 'Bloco de ações', telas: [] },
          { id: 'so-act-macro-cancel', name: 'Cancelar ações de macro', telas: [] },
          { id: 'so-act-macro-delete', name: 'Excluir macro', telas: [] },
          { id: 'so-act-macro-run', name: 'Executar macro', telas: [] },
        ],
      },
      {
        id: 'action-messaging',
        name: 'Mensagem',
        subOptions: [
          { id: 'so-act-msg-sms', name: 'Enviar SMS', telas: [] },
          { id: 'so-act-msg-email', name: 'Enviar e-mail', telas: [] },
          { id: 'so-act-msg-whatsapp', name: 'Enviar via WhatsApp (Beta)', telas: [] },
        ],
      },
      {
        id: 'action-media',
        name: 'Mídia',
        subOptions: [
          { id: 'so-act-media-control', name: 'Controlar mídia', telas: [] },
          { id: 'so-act-media-record', name: 'Gravar do microfone', telas: [] },
          { id: 'so-act-media-play-stop', name: 'Reproduzir/Parar som', telas: [] },
        ],
      },
      {
        id: 'action-notification',
        name: 'Notificação',
        subOptions: [
          { id: 'so-act-notif-led', name: 'Ativar/Desativar LED de notificação', telas: [] },
          { id: 'so-act-notif-heads-up', name: 'Ativar/Desativar heads-up', telas: [] },
          { id: 'so-act-notif-sound', name: 'Definir som de notificação', telas: [] },
          { id: 'so-act-notif-dialog', name: 'Exibir caixa de diálogo', telas: [] },
          { id: 'so-act-notif-show', name: 'Exibir notificação', telas: [] },
          { id: 'so-act-notif-bubble', name: 'Exibir notificação de bolha', telas: [] },
          { id: 'so-act-notif-interact', name: 'Interação de notificação', telas: [] },
          { id: 'so-act-notif-edge-light', name: 'Luz de notificação de borda', telas: [] },
          { id: 'so-act-notif-popup', name: 'Mensagem de pop-up', telas: [] },
          { id: 'so-act-notif-remove', name: 'Remover notificações', telas: [] },
          { id: 'so-act-notif-reply', name: 'Responder notificação', telas: [] },
          { id: 'so-act-notif-restore', name: 'Restaurar notificações ocultas', telas: [] },
          { id: 'so-act-notif-animation', name: 'Sobreposição de animação', telas: [] },
        ],
      },
      {
        id: 'action-logs',
        name: 'Registros',
        subOptions: [
          { id: 'so-act-log-open', name: 'Abrir os registros do MacroDroid', telas: [] },
          { id: 'so-act-log-calendar-add', name: 'Calendário - Adicionar evento', telas: [] },
          { id: 'so-act-log-export', name: 'Exportar registro', telas: [] },
          { id: 'so-act-log-clear', name: 'Limpar registros', telas: [] },
          { id: 'so-act-log-log-event', name: 'Registrar evento', telas: [] },
        ],
      },
      {
        id: 'action-screen',
        name: 'Tela',
        subOptions: [
          { id: 'so-act-screen-touch-lock', name: 'Bloquear Toques na Tela', telas: [] },
          { id: 'so-act-screen-brightness', name: 'Brilho', telas: [] },
          { id: 'so-act-screen-timeout', name: 'Definir o tempo limite da tela', telas: [] },
          { id: 'so-act-screen-dim', name: 'Escurecer a tela', telas: [] },
          { id: 'so-act-screen-force-rotate', name: 'Forçar rotação da tela', telas: [] },
          { id: 'so-act-screen-read-content', name: 'Ler conteúdo da tela', telas: [] },
          { id: 'so-act-screen-read-screenshot', name: 'Ler o conteúdo da captura de ecrã', telas: [] },
          { id: 'so-act-screen-on-off', name: 'Ligar/Desligar tela', telas: [] },
          { id: 'so-act-screen-keep-awake', name: 'Manter o aparelho ativo', telas: [] },
          { id: 'so-act-screen-get-view-id', name: 'Obter texto do ID da vista', telas: [] },
          { id: 'so-act-screen-ocr', name: 'Texto da imagem (OCR)', telas: [] },
          { id: 'so-act-screen-check-pixel', name: 'Verificar a cor dos píxeis', telas: [] },
          { id: 'so-act-screen-check-text-screenshot', name: 'Verificar texto na captura de ecrã', telas: [] },
          { id: 'so-act-screen-check-text-screen', name: 'Verificar texto na tela', telas: [] },
        ],
      },
      {
        id: 'action-phone',
        name: 'Telefone',
        subOptions: [
          { id: 'so-act-phone-call-log', name: 'Abrir registro de chamadas', telas: [] },
          { id: 'so-act-phone-auto-answer', name: 'Atender chamada automaticamente', telas: [] },
          { id: 'so-act-phone-contact-via-app', name: 'Contato via aplicativo', telas: [] },
          { id: 'so-act-phone-set-ringtone', name: 'Definir toque', telas: [] },
          { id: 'so-act-phone-make-call', name: 'Efetuar chamada', telas: [] },
          { id: 'so-act-phone-clear-log', name: 'Limpar o registro de chamadas', telas: [] },
          { id: 'so-act-phone-get-contacts', name: 'Obter contactos', telas: [] },
          { id: 'so-act-phone-reject-call', name: 'Rejeitar chamada', telas: [] },
        ],
      },
      {
        id: 'action-variables',
        name: 'Variáveis',
        subOptions: [
          {
            id: 'so-act-var-define',
            name: 'Definir variável',
            telas: [
                { id: 't-act-var-1', content: 'Tela 1  Selecione a variável  [ ] Nova Variável [... Lista com variáveis já criadas se houver]  CANCELAR | OK' },
                { id: 't-act-var-2', content: 'Tela 2: [ X ] Nova Variável  * Criar nova variável  [ ] Local  [ ] Global  [... Digite o nome da variável] | botão: [...] (Lista de palavras mágicas, as palavras mágicas não são por "[ ]", são por "{ }")  * Tipo de variável:  Lista: Booleano, inteiro, string, decimal, dicionário e lista  [ ] Criar variável agora [ ] Tornar a variável segura' },
                { id: 't-act-var-3', content: 'Tela 3: [ X ] Local, Booleano, [ X ] Criar variável agora  * Ajustes [Nome da variável]  Lista: [ ] falso, [ ] verdadeiro, [ ] inverter, [ ] `[Prompt de usuário]`, [ ] Variável (mostra lista de variáveis criadas)  CANCELAR | OK' },
            ],
          },
          { id: 'so-act-var-delete', name: 'Eliminar variável', telas: [] },
          { id: 'so-act-var-clear-dict', name: 'Limpar entrada de Dicionário/Lista', telas: [] },
          { id: 'so-act-var-clear-all', name: 'Limpar variáveis', telas: [] },
          { id: 'so-act-var-array-manip', name: 'Manipulação de matrizes', telas: [] },
        ],
      },
      {
        id: 'action-volume',
        name: 'Volume',
        subOptions: [
          {
            id: 'so-act-vol-adjust',
            name: 'Ajustar volume',
            telas: [{ id: 't-act-vol-1', content: 'Tela 1:   Ajustar volume:  [ ] Definir volume em primeiro plano  ---  [ ] Alarme  Valor do cursor | \\/ (Botão de seta pra baixo, lá tem a lista com as variáveis, caso alguma tenha sido criada, e que seja necessário usá-la)  0% — — — 100%  ---  [ ] Mídia / Música  Valor do cursor | \\/  0% — — — 100%  ---  [ ] Notificação  Valor do cursor | \\/  0% — — — 100%  ---  [ ] Chamada  Valor do cursor | \\/  0% — — — 100%  ---  [ ] Sons do Sistema  Valor do cursor | \\/  0% — — — 100%  ---  [ ] Chamada de voz  Valor do cursor | \\/  0% — — — 100%  ---  [ ] Bluetooth  Valor do cursor | \\/  0% — — — 100%  ---  [ ] Acessibilidade  Valor do cursor | \\/  0% — — — 100%  CANCELAR | OK' }],
          },
          { id: 'so-act-vol-speaker', name: 'Alto-falante ligado/desligado', telas: [] },
          { id: 'so-act-vol-up-down', name: 'Aumentar/diminuir volume', telas: [] },
          {
            id: 'so-act-vol-dnd',
            name: 'Modo Prioritário / Não Perturbe',
            telas: [{ id: 't-act-dnd-1', content: 'Tela 1:  Selecione uma opção:  ( ) Permitir tudo ( ) Somente prioridade ( ) Silêncio total  ( ) Somente alarmes  CANCELAR | OK' }],
          },
          { id: 'so-act-vol-show-popup', name: 'Mostrar pop-up de volume', telas: [] },
          { id: 'so-act-vol-silent', name: 'Silencioso (sem vibração)', telas: [] },
          { id: 'so-act-vol-vibrate', name: 'Vibração ativada/desativada', telas: [] },
        ],
      },
  ],
  constraints: [
    {
        id: 'constraint-battery',
        name: 'Bateria/Potência',
        subOptions: [
          { id: 'so-res-bat-power', name: 'Alimentação externa', telas: [] },
          { id: 'so-res-bat-saver', name: 'Estado de Economia de Bateria', telas: [] },
          { id: 'so-res-bat-level', name: 'Nível da bateria', telas: [] },
          { id: 'so-res-bat-temp', name: 'Temperatura da bateria', telas: [] },
        ],
      },
      {
        id: 'constraint-connectivity',
        name: 'Conectividade',
        subOptions: [
          { id: 'so-res-conn-data', name: 'Dados móveis ligados/desligados', telas: [] },
          { id: 'so-res-conn-ip', name: 'Endereço IP', telas: [] },
          { id: 'so-res-conn-bt', name: 'Estado do Bluetooth', telas: [] },
          { id: 'so-res-conn-gps', name: 'Estado do GPS', telas: [] },
          { id: 'so-res-conn-wifi', name: 'Estado do Wi-Fi', telas: [] },
          { id: 'so-res-conn-hotspot', name: 'Estado do ponto de acesso Wi-Fi', telas: [] },
          { id: 'so-res-conn-loc-mode', name: 'Modo da localização', telas: [] },
          { id: 'so-res-conn-roaming', name: 'Roaming', telas: [] },
          { id: 'so-res-conn-signal', name: 'Status do sinal de celular', telas: [] },
        ],
      },
      {
        id: 'constraint-datetime',
        name: 'Data/Hora',
        subOptions: [
          { id: 'so-res-dt-stopwatch', name: 'Cronômetro', telas: [] },
          { id: 'so-res-dt-day-week', name: 'Dia da semana', telas: [] },
          { id: 'so-res-dt-day-month', name: 'Dia do mês', telas: [] },
          { id: 'so-res-dt-calendar', name: 'Entrada de calendário', telas: [] },
          { id: 'so-res-dt-time', name: 'Hora do dia', telas: [] },
          { id: 'so-res-dt-month', name: 'Mês do ano', telas: [] },
          { id: 'so-res-dt-sun', name: 'Nascer/Pôr do sol', telas: [] },
        ],
      },
      {
        id: 'constraint-macrodroid',
        name: 'Específico do MacroDroid',
        subOptions: [
          { id: 'so-res-md-floating-button', name: 'Botão flutuante', telas: [] },
          { id: 'so-res-md-category', name: 'Categoria ativada/desativada', telas: [] },
          { id: 'so-res-md-compare', name: 'Comparar valores', telas: [] },
          { id: 'so-res-md-logic', name: 'E / OU / OU... OU / NÃO', telas: [] },
          { id: 'so-res-md-drawer', name: 'Estado da gaveta do MacroDroid', telas: [] },
          { id: 'so-res-md-quicktile', name: 'Estado rápido do bloco', telas: [] },
          { id: 'so-res-md-triggered', name: 'Gatilho disparado', telas: [] },
          { id: 'so-res-md-running', name: 'Macro em execução', telas: [] },
          { id: 'so-res-md-enabled', name: 'Macro habilitada/desabilitada', telas: [] },
          { id: 'so-res-md-invoked', name: 'Macro(s) invocada(s) ou não recentemente', telas: [] },
          { id: 'so-res-md-mode', name: 'Modo do MacroDroid', telas: [] },
          { id: 'so-res-md-invoke-method', name: 'Método de invocação da macro', telas: [] },
          { id: 'so-res-md-floating-text', name: 'Texto Flutuante', telas: [] },
          { id: 'so-res-md-variable', name: 'Variável do MacroDroid', telas: [] },
        ],
      },
      {
        id: 'constraint-device-state',
        name: 'Estado do Dispositivo',
        subOptions: [
          { id: 'so-res-dev-app-installed', name: 'Aplicativo instalado', telas: [] },
          { id: 'so-res-dev-app-running', name: 'Aplicativo rodando', telas: [] },
          { id: 'so-res-dev-sys-setting', name: 'Configuração de sistema', telas: [] },
          { id: 'so-res-dev-clipboard', name: 'Conteúdos da área de transferência', telas: [] },
          { id: 'so-res-dev-locked', name: 'Dispositivo bloqueado/desbloqueado', telas: [] },
          { id: 'so-res-dev-root', name: 'Dispositivo com acesso root', telas: [] },
          { id: 'so-res-dev-nfc', name: 'Estado do NFC', telas: [] },
          { id: 'so-res-dev-vpn', name: 'Estado do VPN', telas: [] },
          { id: 'so-res-dev-adb-hack', name: 'Hack ADB aplicado', telas: [] },
          { id: 'so-res-dev-torch', name: 'Lanterna Ligada/Desligada', telas: [] },
          { id: 'so-res-dev-airplane', name: 'Modo avião', telas: [] },
          { id: 'so-res-dev-roaming', name: 'Roaming ativado', telas: [] },
          { id: 'so-res-dev-autorotate', name: 'Rotação automática', telas: [] },
          { id: 'so-res-dev-autosync', name: 'Sincronização automática', telas: [] },
          { id: 'so-res-dev-uptime', name: 'Tempo desde a inicialização', telas: [] },
          { id: 'so-res-dev-screen-text', name: 'Texto de apresentação', telas: [] },
        ],
      },
      {
        id: 'constraint-location',
        name: 'Localização',
        subOptions: [
          { id: 'so-res-loc-geofence', name: 'Perímetro (localização)', telas: [] },
          { id: 'so-res-loc-cell-towers', name: 'Torres de celular', telas: [] },
        ],
      },
      {
        id: 'constraint-media',
        name: 'Mídia',
        subOptions: [
          { id: 'so-res-media-headset', name: 'Conexão do fone de ouvido', telas: [] },
          { id: 'so-res-media-music', name: 'Música ativa', telas: [] },
        ],
      },
      {
        id: 'constraint-notification',
        name: 'Notificação',
        subOptions: [
          { id: 'so-res-notif-dnd', name: 'Modo Prioritário / Não Perturbe', telas: [] },
          { id: 'so-res-notif-present', name: 'Notificação presente', telas: [] },
          { id: 'so-res-notif-volume', name: 'Volume das notificações', telas: [] },
        ],
      },
      {
        id: 'constraint-sensors',
        name: 'Sensores',
        subOptions: [
          { id: 'so-res-sensor-face-up', name: 'Dispositivo voltado para cima/baixo', telas: [] },
          { id: 'so-res-sensor-orientation', name: 'Orientação do dispositivo', telas: [] },
          { id: 'so-res-sensor-light', name: 'Sensor de luz', telas: [] },
          { id: 'so-res-sensor-proximity', name: 'Sensor de proximidade', telas: [] },
        ],
      },
      {
        id: 'constraint-screen-speaker',
        name: 'Tela e alto-falante',
        subOptions: [
          { id: 'so-res-ss-speaker', name: 'Alto-falante ligado/desligado', telas: [] },
          { id: 'so-res-ss-brightness', name: 'Brilho', telas: [] },
          { id: 'so-res-ss-ambient', name: 'Estado do ecrã ambiente', telas: [] },
          { id: 'so-res-ss-volume-level', name: 'Nível do volume', telas: [] },
          { id: 'so-res-ss-screen-on', name: 'Tela ligada/desligada', telas: [] },
          { id: 'so-res-ss-dark-theme', name: 'Tema escuro', telas: [] },
          { id: 'so-res-ss-ring-volume', name: 'Volume da campainha', telas: [] },
        ],
      },
      {
        id: 'constraint-phone',
        name: 'Telefone',
        subOptions: [
          { id: 'so-res-phone-call-state', name: 'Estado de chamada', telas: [] },
          { id: 'so-res-phone-ringing', name: 'Telefone tocando', telas: [] },
        ],
      },
  ],
  variables: [],
};
